### ISSUE TITLE
i can't install random and time

### ISSUE THREAD

**Issue by islammekatel** [BagavanMM/giveaway-ig#1]
![Capture d’écran 2023-08-31 165004](https://github.com/BagavanMM/autotag-ig-bot/assets/143731144/cbeb1aa3-3334-4a40-b115-0e2d66c71ca6)

**Comment by BagavanMM** [comment]
Time and random are built-in packages of python so it should already be installed. (I've updated requirements.txt so that it doesn't include those two packages)
Let me know if you're still running into issues
